# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layout_root = QtWidgets.QHBoxLayout(self.centralwidget)
        self.layout_root.setObjectName("layout_root")
        self.leftColumn = QtWidgets.QVBoxLayout()
        self.leftColumn.setObjectName("leftColumn")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.leftColumn.addWidget(self.titleLabel)
        self.stopInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.stopInput.setObjectName("stopInput")
        self.leftColumn.addWidget(self.stopInput)
        self.checkButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.checkButton.setObjectName("checkButton")
        self.leftColumn.addWidget(self.checkButton)
        self.historyLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.historyLabel.setObjectName("historyLabel")
        self.leftColumn.addWidget(self.historyLabel)
        self.recentContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.recentContainer.setObjectName("recentContainer")
        self.recentGrid = QtWidgets.QGridLayout(self.recentContainer)
        self.recentGrid.setSpacing(8)
        self.recentGrid.setObjectName("recentGrid")
        self.leftColumn.addWidget(self.recentContainer)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.leftColumn.addItem(spacerItem)
        self.layout_root.addLayout(self.leftColumn)
        self.rightColumn = QtWidgets.QVBoxLayout()
        self.rightColumn.setObjectName("rightColumn")
        self.timestampLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.timestampLabel.setObjectName("timestampLabel")
        self.rightColumn.addWidget(self.timestampLabel)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_scroll = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_scroll.setObjectName("verticalLayout_scroll")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.rightColumn.addWidget(self.scrollArea)
        self.layout_root.addLayout(self.rightColumn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMT PALMA - Bus Arrivals"))
        self.titleLabel.setText(_translate("MainWindow", "EMT PALMA"))
        self.stopInput.setPlaceholderText(_translate("MainWindow", "Enter stop number..."))
        self.checkButton.setText(_translate("MainWindow", "Consultar parada"))
        self.historyLabel.setText(_translate("MainWindow", "Historial:"))
        self.timestampLabel.setText(_translate("MainWindow", "Last updated: —"))
